### ISSUE TITLE
PHP-mysql-MODBUS

### ISSUE THREAD

**Issue by meetathool** [meetathool/Meeta#1]
Kindly help to connect/fetch MODBUS data to mysql database using PHP.

**Comment by meetathool** [comment]
Pls help me. following error is coming while connecting

readCoils: START
Connected
Packet: 9ebb00000006010100010002
Send
Wait data ... 
Wait data ... 
Wait data ... 
Wait data ... 
Wait data ... 
Wait data ... 
Wait data ... 
Wait data ... 
Wait data ... 
Wait data ... 
Wait data ... 
Wait data ... 
Wait data ... 
Wait data ... 
Wait data ... 
Wait data ... 
exception 'Exception' with message 'Watchdog time expired [ 5 sec]!!! Connection to 192.168.99.7 is not established.' in C:\xampp\htdocs\CRMS\Phpmodbus\ModbusMaster.php:168 Stack trace: #0 C:\xampp\htdocs\CRMS\Phpmodbus\ModbusMaster.php(237): ModbusMaster->rec() #1 C:\xampp\htdocs\CRMS\Phpmodbus\ModbusMaster.php(259): ModbusMaster->readCoils('1', '00001', '2') #2 C:\xampp\htdocs\CRMS\ConnectDeviceSubmit.php(45): ModbusMaster->fc1('1', '00001', '2') #3 C:\xampp\htdocs\CRMS\ConnectDeviceSubmit.php(108): getRecForFunctionCode('1', 1, Object(ModbusMaster)) #4 C:\xampp\htdocs\CRMS\ConnectDeviceSubmit.php(9): connectDevice() #5 {main}127.0.0.1
